<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="CodeIgniter Application Test Suite" tests="6" assertions="4" failures="1" errors="2" time="0.146940">
    <testsuite name="Company_test" file="/var/www/tab_api/application/tests/controllers/Company_test.php" tests="3" assertions="1" failures="0" errors="2" time="0.084270">
      <testcase name="test_index" class="Company_test" file="/var/www/tab_api/application/tests/controllers/Company_test.php" line="13" assertions="0" time="0.044048">
        <error type="PHPUnit_Framework_ExceptionWrapper">Company_test::test_index
RuntimeException: Cannot modify header information - headers already sent by (output started at /usr/share/php/PHPUnit/Util/Printer.php:134) on line 2190 in file /var/www/tab_api/application/libraries/REST_Controller.php

/var/www/tab_api/application/tests/_ci_phpunit_test/CIPHPUnitTestCase.php:169
/var/www/tab_api/application/libraries/REST_Controller.php:2190
/var/www/tab_api/application/libraries/REST_Controller.php:471
/var/www/tab_api/application/controllers/Company.php:15
/var/www/tab_api/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php:343
/var/www/tab_api/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php:297
/var/www/tab_api/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php:160
/var/www/tab_api/application/tests/_ci_phpunit_test/CIPHPUnitTestCase.php:144
/var/www/tab_api/application/tests/controllers/Company_test.php:15
</error>
      </testcase>
      <testcase name="test_method_404" class="Company_test" file="/var/www/tab_api/application/tests/controllers/Company_test.php" line="19" assertions="0" time="0.027316">
        <error type="PHPUnit_Framework_ExceptionWrapper">Company_test::test_method_404
RuntimeException: Cannot modify header information - headers already sent by (output started at /usr/share/php/PHPUnit/Util/Printer.php:134) on line 2190 in file /var/www/tab_api/application/libraries/REST_Controller.php

/var/www/tab_api/application/tests/_ci_phpunit_test/CIPHPUnitTestCase.php:169
/var/www/tab_api/application/libraries/REST_Controller.php:2190
/var/www/tab_api/application/libraries/REST_Controller.php:471
/var/www/tab_api/application/controllers/Company.php:15
/var/www/tab_api/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php:343
/var/www/tab_api/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php:297
/var/www/tab_api/application/tests/_ci_phpunit_test/CIPHPUnitTestRequest.php:160
/var/www/tab_api/application/tests/_ci_phpunit_test/CIPHPUnitTestCase.php:144
/var/www/tab_api/application/tests/controllers/Company_test.php:21
</error>
      </testcase>
      <testcase name="test_APPPATH" class="Company_test" file="/var/www/tab_api/application/tests/controllers/Company_test.php" line="25" assertions="1" time="0.012906"/>
    </testsuite>
    <testsuite name="User_test" file="/var/www/tab_api/application/tests/controllers/User.test.php" tests="3" assertions="3" failures="1" errors="0" time="0.062670">
      <testcase name="test_index" class="User_test" file="/var/www/tab_api/application/tests/controllers/User.test.php" line="13" assertions="1" time="0.027570">
        <failure type="PHPUnit_Framework_ExpectationFailedException">User_test::test_index
Failed asserting that 'User/signup is not found' contains "&lt;title&gt;Welcome to CodeIgniter&lt;/title&gt;".

/var/www/tab_api/application/tests/controllers/User.test.php:16
</failure>
      </testcase>
      <testcase name="test_method_404" class="User_test" file="/var/www/tab_api/application/tests/controllers/User.test.php" line="19" assertions="1" time="0.024710"/>
      <testcase name="test_APPPATH" class="User_test" file="/var/www/tab_api/application/tests/controllers/User.test.php" line="25" assertions="1" time="0.010390"/>
    </testsuite>
  </testsuite>
</testsuites>
